// <auto-generated />
using System;
using Albergue_aspnet_DAS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Albergue_aspnet_DAS.Migrations
{
    [DbContext(typeof(BdAlbergueAspnetContext))]
    [Migration("20250216130726_asd")]
    partial class asd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbAdopcion", b =>
                {
                    b.Property<int>("IdAdop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_adop");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdop"));

                    b.Property<string>("DireccionUs")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion_us");

                    b.Property<string>("DniUs")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("dni_us")
                        .IsFixedLength();

                    b.Property<DateOnly?>("FechaAdop")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adop");

                    b.Property<int?>("IdMas")
                        .HasColumnType("int")
                        .HasColumnName("id_mas");

                    b.Property<int?>("IdUs")
                        .HasColumnType("int")
                        .HasColumnName("id_us");

                    b.Property<string>("Obs10Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs10_adop");

                    b.Property<string>("Obs1Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs1_adop");

                    b.Property<string>("Obs2Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs2_adop");

                    b.Property<string>("Obs3Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs3_adop");

                    b.Property<string>("Obs4Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs4_adop");

                    b.Property<string>("Obs5Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs5_adop");

                    b.Property<string>("Obs6Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs6_adop");

                    b.Property<string>("Obs7Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs7_adop");

                    b.Property<string>("Obs8Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs8_adop");

                    b.Property<string>("Obs9Adop")
                        .HasColumnType("text")
                        .HasColumnName("obs9_adop");

                    b.Property<string>("TelefonoUs")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("telefono_us");

                    b.HasKey("IdAdop")
                        .HasName("PK__TB_ADOPC__B431877B7ECAC70A");

                    b.HasIndex("IdMas");

                    b.HasIndex("IdUs");

                    b.ToTable("TB_ADOPCION", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbAlbergue", b =>
                {
                    b.Property<int>("IdAlb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alb");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlb"));

                    b.Property<int?>("CapacidadAlb")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_alb");

                    b.Property<string>("CorreoAlb")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo_alb");

                    b.Property<string>("DireccionAlb")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion_alb");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int?>("IdDist")
                        .HasColumnType("int")
                        .HasColumnName("id_dist");

                    b.Property<int?>("IdProv")
                        .HasColumnType("int")
                        .HasColumnName("id_prov");

                    b.Property<string>("NombreAlb")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_alb");

                    b.HasKey("IdAlb")
                        .HasName("PK__TB_ALBER__6BE93B0C3C2AB683");

                    b.HasIndex("IdDist");

                    b.HasIndex("IdProv");

                    b.ToTable("TB_ALBERGUE", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbDistrito", b =>
                {
                    b.Property<int>("IdDist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dist");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDist"));

                    b.Property<string>("DescripcionDist")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion_dist");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdDist")
                        .HasName("PK__TB_DISTR__972B439DCE608B8D");

                    b.ToTable("TB_DISTRITOS", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbHistorialAtencionMascotum", b =>
                {
                    b.Property<int>("IdHis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_his");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHis"));

                    b.Property<string>("ApellidosMed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos_med");

                    b.Property<string>("CodColegiatura")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cod_colegiatura");

                    b.Property<string>("ConsultaMedica")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("consulta_medica");

                    b.Property<int>("IdMas")
                        .HasColumnType("int")
                        .HasColumnName("id_mas");

                    b.Property<string>("NombreMed")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_med");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.HasKey("IdHis")
                        .HasName("PK__TB_HISTO__D6EA82DD553CD8C8");

                    b.HasIndex("IdMas");

                    b.ToTable("TB_HISTORIAL_ATENCION_MASCOTA", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbMascotum", b =>
                {
                    b.Property<int>("IdMas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMas"));

                    b.Property<string>("ColorMas")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color_mas");

                    b.Property<int?>("EdadMas")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("edad_mas")
                        .HasComputedColumnSql("(datediff(year,[fecha_nac_mas],getdate()))", false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaNacMas")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nac_mas");

                    b.Property<int>("IdAlb")
                        .HasColumnType("int")
                        .HasColumnName("id_alb");

                    b.Property<int>("IdRazMas")
                        .HasColumnType("int")
                        .HasColumnName("id_raz_mas");

                    b.Property<int>("IdTipMas")
                        .HasColumnType("int")
                        .HasColumnName("id_tip_mas");

                    b.Property<byte[]>("ImagenMas")
                        .HasColumnType("image")
                        .HasColumnName("imagen_mas");

                    b.Property<string>("NombreMas")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre_mas");

                    b.Property<string>("SexoMas")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("sexo_mas")
                        .IsFixedLength();

                    b.Property<string>("TamanioMas")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tamaño_mas");

                    b.HasKey("IdMas")
                        .HasName("PK__TB_MASCO__6C8AD5B02239F910");

                    b.HasIndex("IdAlb");

                    b.HasIndex("IdRazMas");

                    b.HasIndex("IdTipMas");

                    b.ToTable("TB_MASCOTA", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbProvincia", b =>
                {
                    b.Property<int>("IdProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_prov");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProv"));

                    b.Property<string>("DescripcionProv")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion_prov");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdProv")
                        .HasName("PK__TB_PROVI__0DA3485D97828659");

                    b.ToTable("TB_PROVINCIAS", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbRazaMascotum", b =>
                {
                    b.Property<int>("IdRazMas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_raz_mas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRazMas"));

                    b.Property<string>("DescripcionRazMas")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("descripcion_raz_mas");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdRazMas")
                        .HasName("PK__TB_RAZA___7290F9FDDD9B4FF3");

                    b.ToTable("TB_RAZA_MASCOTA", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbRolesUsuario", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__TB_ROLES__6ABCB5E073930C9B");

                    b.ToTable("TB_ROLES_USUARIO", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbTipoMascotum", b =>
                {
                    b.Property<int>("IdTipMas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tip_mas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipMas"));

                    b.Property<string>("DescripcionTipMas")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("descripcion_tip_mas");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.HasKey("IdTipMas")
                        .HasName("PK__TB_TIPO___1904A0A36E0CBF11");

                    b.ToTable("TB_TIPO_MASCOTA", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbUsuario", b =>
                {
                    b.Property<int>("IdUs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_us");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUs"));

                    b.Property<string>("ClaveUs")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("clave_us");

                    b.Property<string>("CorreoUs")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("correo_us");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<byte[]>("ImagenUs")
                        .HasColumnType("image")
                        .HasColumnName("imagen_us");

                    b.Property<string>("NombreUs")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre_us");

                    b.HasKey("IdUs")
                        .HasName("PK__TB_USUAR__014848A59A0E52CB");

                    b.HasIndex("IdRol");

                    b.ToTable("TB_USUARIOS", (string)null);
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbAdopcion", b =>
                {
                    b.HasOne("Albergue_aspnet_DAS.Models.TbMascotum", "IdMasNavigation")
                        .WithMany("TbAdopcions")
                        .HasForeignKey("IdMas")
                        .HasConstraintName("Fk_ADOPID_MAS_CODIGO");

                    b.HasOne("Albergue_aspnet_DAS.Models.TbUsuario", "IdUsNavigation")
                        .WithMany("TbAdopcions")
                        .HasForeignKey("IdUs")
                        .HasConstraintName("Fk_ADOPID_USU_CODIGO");

                    b.Navigation("IdMasNavigation");

                    b.Navigation("IdUsNavigation");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbAlbergue", b =>
                {
                    b.HasOne("Albergue_aspnet_DAS.Models.TbDistrito", "oDistrito")
                        .WithMany("TbAlbergues")
                        .HasForeignKey("IdDist")
                        .HasConstraintName("Fk_ADIST_CODIGO");

                    b.HasOne("Albergue_aspnet_DAS.Models.TbProvincia", "oProvincia")
                        .WithMany("TbAlbergues")
                        .HasForeignKey("IdProv")
                        .HasConstraintName("Fk_APROV_CODIGO");

                    b.Navigation("oDistrito");

                    b.Navigation("oProvincia");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbHistorialAtencionMascotum", b =>
                {
                    b.HasOne("Albergue_aspnet_DAS.Models.TbMascotum", "IdMasNavigation")
                        .WithMany("TbHistorialAtencionMascota")
                        .HasForeignKey("IdMas")
                        .IsRequired()
                        .HasConstraintName("Fk_HIS_CODIGO");

                    b.Navigation("IdMasNavigation");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbMascotum", b =>
                {
                    b.HasOne("Albergue_aspnet_DAS.Models.TbAlbergue", "oAlbergue")
                        .WithMany("TbMascota")
                        .HasForeignKey("IdAlb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Mraz_ALB_CODIGO");

                    b.HasOne("Albergue_aspnet_DAS.Models.TbRazaMascotum", "oRazaMascota")
                        .WithMany("TbMascota")
                        .HasForeignKey("IdRazMas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Mraz_MAs_CODIGO");

                    b.HasOne("Albergue_aspnet_DAS.Models.TbTipoMascotum", "oTipoMascota")
                        .WithMany("TbMascota")
                        .HasForeignKey("IdTipMas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_MTIP_MAS_CODIGO");

                    b.Navigation("oAlbergue");

                    b.Navigation("oRazaMascota");

                    b.Navigation("oTipoMascota");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbUsuario", b =>
                {
                    b.HasOne("Albergue_aspnet_DAS.Models.TbRolesUsuario", "IdRolNavigation")
                        .WithMany("TbUsuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("Fk_USUID_ROL_CODIGO");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbAlbergue", b =>
                {
                    b.Navigation("TbMascota");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbDistrito", b =>
                {
                    b.Navigation("TbAlbergues");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbMascotum", b =>
                {
                    b.Navigation("TbAdopcions");

                    b.Navigation("TbHistorialAtencionMascota");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbProvincia", b =>
                {
                    b.Navigation("TbAlbergues");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbRazaMascotum", b =>
                {
                    b.Navigation("TbMascota");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbRolesUsuario", b =>
                {
                    b.Navigation("TbUsuarios");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbTipoMascotum", b =>
                {
                    b.Navigation("TbMascota");
                });

            modelBuilder.Entity("Albergue_aspnet_DAS.Models.TbUsuario", b =>
                {
                    b.Navigation("TbAdopcions");
                });
#pragma warning restore 612, 618
        }
    }
}
